---
- name: Prepare bare target for the Artemis collection
  hosts: artemislocal
  become: true

  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - ubuntu

  tasks:
    - name: Install git and acl
      ansible.builtin.apt:
        name:
          - git
          - acl
        state: present
        update_cache: true