#!/usr/bin/env bash
# Lab tooling: replace every hashi_vault lookup expression in an UNPACKED
# remote-ansible package with a freshly generated dummy value, so the package
# can be boot-tested without a Vault. This automates the "Without Vault" path
# of the package README.
#
# Usage:
#   ./generate-dummy-secrets.sh <unpacked-package-dir>   from anywhere, or
#   ./generate-dummy-secrets.sh                          copied into the package root, preflight-style
#
# Never run this against real deployment values, and never commit the modified
# package anywhere: after this script the values files contain plaintext
# (dummy) secrets.
#
# Redeploying with a freshly generated artemis_database_password against a VM
# whose MySQL data volume was initialized by an earlier deployment yields
# "Access denied" crash loops: MySQL applies credentials only on first
# initialization, so wipe that volume first (or keep the old password).
set -euo pipefail

if [ $# -gt 1 ]; then
    echo "Usage: $0 [unpacked-package-dir]" >&2
    exit 1
fi
if [ $# -eq 1 ]; then
    PACKAGE_DIR="$1"
else
    PACKAGE_DIR=$(cd "$(dirname "$0")" && pwd)
fi
# Only operate on something that is unmistakably an unpacked remote-ansible
# package - never on the lab's own hand-written inventory.
if [ ! -d "$PACKAGE_DIR/inventory/group_vars" ] || [ ! -f "$PACKAGE_DIR/metadata/vault-references.json" ]; then
    echo "Refusing: '$PACKAGE_DIR' does not look like an unpacked remote-ansible package" >&2
    echo "(expected inventory/group_vars/ and metadata/vault-references.json)." >&2
    echo "Pass the unpacked package directory as argument, or copy this script into the package root and run it there." >&2
    exit 1
fi

EXPRESSIONS=$(grep -rhoE "\{\{ lookup\('hashi_vault', '[^']+'\)\.get\('[^']+'\) \}\}" "$PACKAGE_DIR/inventory" | sort -u || true)
if [ -z "$EXPRESSIONS" ]; then
    echo "No hashi_vault lookup expressions found under $PACKAGE_DIR/inventory - nothing to do (already replaced?)."
    exit 0
fi

COUNT=0
while IFS= read -r expr; do
    field=$(printf '%s' "$expr" | sed -E "s/.*\.get\('([^']+)'\).*/\1/")
    vault_path=$(printf '%s' "$expr" | sed -E "s/.*lookup\('hashi_vault', '([^']+)'\).*/\1/")
    # Value shape by field type: URL-typed fields need a syntactically valid URL or
    # Artemis fails parsing them at boot (.invalid is reserved and never resolves).
    # All generated values are alphanumeric only - no '/', '+', '=' - so
    # double-click selection and copy-paste stay reliable. The JWT stays a valid
    # base64 string (plain [A-Za-z0-9], length a multiple of 4) and decodes to
    # more than the 64 bytes HS512 requires; the admin password is the one a
    # human types into the login form, so it is deliberately short.
    case "$field" in
        url | endpoint | *_url | *_endpoint)
            value="https://dummy-$(basename "$vault_path").invalid" ;;
        jhipster_jwt)
            value=$(openssl rand -base64 120 | tr -d '/+=\n' | cut -c1-88) ;;
        internal_admin)
            value=$(openssl rand -base64 48 | tr -d '/+=\n' | cut -c1-24) ;;
        *)
            value=$(openssl rand -base64 64 | tr -d '/+=\n' | cut -c1-48) ;;
    esac
    case "$expr" in
        *"kv/data/artemis/common/"*)
            echo "WARNING: '$field' authenticates against an external service; the dummy value renders, but that integration will not actually work." ;;
    esac
    grep -rlF "$expr" "$PACKAGE_DIR/inventory" | while IFS= read -r file; do
        EXPR="$expr" VALUE="$value" perl -pi -e 's/\Q$ENV{EXPR}\E/$ENV{VALUE}/g' "$file"
        echo "  $file: $field -> dummy value"
    done
    COUNT=$((COUNT + 1))
done <<< "$EXPRESSIONS"

# The generated secrets file claims to hold only lookup expressions; make its comment tell the truth now.
grep -rl "every value below is a Vault lookup" "$PACKAGE_DIR/inventory" 2>/dev/null | while IFS= read -r file; do
    perl -pi -e 's/^# Secret values are never stored in this package; every value below is a Vault lookup$/# DUMMY VALUES generated by generate-dummy-secrets.sh for lab testing only./; s/^# expression\. See README\.md for the Vault setup and the no-Vault alternative\.$/# Do not commit this file and do not reuse these values anywhere real./' "$file"
done

echo "Replaced $COUNT distinct vault lookup(s) with generated dummy values."
echo "The Artemis admin login password is now the artemis_internal_admin_password value in the target group's secrets.yml."
